### ISSUE TITLE
TODO | Bugs

### ISSUE THREAD

**Issue by thanhngan22** [fit-hcmus-k21/gallery#15]
## Bugs
- [ ] lỗi chưa refresh UI khi ảnh đã tải xong/ kéo data khi login 
- [x] xóa ảnh bị văng
- [x] thiết lập ảnh đại diện mặc định cho album khi tạo
- [ ] 1 album khi được bảo mật cần reset ảnh đại diện album thành icon private ...
___

## Tính năng nhỏ/ Cập nhật UI (rảnh làm sau)
- [ ] Bắt sự kiện thêm ảnh từ zalo/mess/ sceen capture ?
- [x] Thêm item Thêm TAG/ description... cho ảnh trên menu chỉnh ảnh 
- [x] Coi lại cái Đăng ký gg/fb
- [ ] Chỉnh lại hiển thị ảnh dạng list: imageview/ | vài thông tin ảnh
- [x] Thêm thanh loading cho đồng bộ/ sao lưu
- [x] Kéo dữ liệu từ server về nếu đăng nhập thành công mà local kh có data
- [x] Chỉnh lại cái cấp phép truy cập và lấy hết ảnh trong đt
- [x] Cài đặt album đặc biệt: private/bin
- [x] Chuyển download qua url (cả video, img ?) qua tab fragment media items, click add btn hiện pop up...
