### ISSUE TITLE
main-features | checklist

### ISSUE THREAD

**Issue by thanhngan22** [fit-hcmus-k21/gallery#2]
### Basic: (8)
- [ ] 3. `Quản lý Album`: Tổ chức ảnh theo album yêu thích, album ảnh từ Facebook, Zalo. Album ảnh được tạo bởi người dùng. Tạo, chỉnh sửa, xóa các album ảnh.
- [ ] 4. `Sắp xếp ảnh`: Sắp xếp dựa vào tên, ngày chụp, thẻ, v.v.
- [ ] 9. `Tìm kiếm ảnh`: Chức năng tìm kiếm ảnh theo tên, theo loại extension của ảnh, kích thước ảnh.
- [ ] 11. `Xóa ảnh`: Xóa ảnh tạm thời sẽ đưa ảnh vào thùng rác, ảnh có thể phục hồi lại vào album hoặc tiếp tục xóa đi vĩnh viễn.
- [ ] 14. `Ghi chú ảnh`: Mỗi ảnh sẽ có tính năng đặt làm ảnh yêu thích, ghi chú lên ảnh.
- [ ] 16. `Đặt ảnh làm hình nền màn hình khóa, màn hình chính`: Ảnh được chọn sẽ có chức năng được chọn làm màn hình chính hoặc màn hình khóa cho thiết bị.
- [ ] 17. `Thống kê`: Chức năng thống kê sẽ thống kê toàn bộ về số lượng ảnh có trong album, tổng kích thước của ảnh và video.
- [ ] 20. `Xem ảnh`: Cho phép người dùng xem ảnh ở chế độ lưới, danh sách với thông tin kèm theo hoặc dạng toàn màn hình.
___

### Intermediate: (7)
- [ ] 5. `Thêm ảnh`: Thêm ảnh, cho phép người dùng thêm ảnh từ thiết bị hoặc từ camera.
- [ ] 6. `Chỉnh sửa ảnh và bộ lọc`: Tập hợp các công cụ chỉnh sửa ảnh, vẽ, cắt, xoay ảnh, filter ảnh về màu sắc, độ tương phản.
- [ ] 7. `Xem và hiển thị ảnh`: Xem ảnh có thêm chế độ phóng to, thu nhỏ, xoay 90 độ, 360 độ.
- [ ] 8. `Tải ảnh lên thông qua QR Code`: Cho phép người dùng tải ảnh lên internet và tạo QR code.
- [ ] 10. `Chia sẻ ảnh qua Internet`: Chức năng chia sẻ, gửi ảnh qua các nền tảng Facebook, Zalo, Gmail.
- [ ] 13. `Đồng bộ hóa và sao lưu`: Tiếng hành đồng bộ hóa ảnh ở ứng dụng lên Drive.
- [ ] 15. `Chuyển đổi sang text`: Các dòng văn bản trong ảnh sẽ được xử lý và chuyển đổi sang text để người dùng có thể sao chép.

___

### Advanced: (5)
- [ ] 1. `Đăng ký đăng nhập`: Sử dụng vân tay, đăng ký tài khoản dựa trên tài khoản Google, Facebook có sẵn.
- [ ] 2. `Tạo câu chuyện`: Hệ thống chọn ngẫu nhiên ảnh, gif, video trong khoảng thời gian nhất định, tự động tổ chức ghép nhạc thành 1 video ngắn dạng Tiktok.
- [ ] 12.` Bảo mật và quyền truy cập`: Album ảnh được bảo mật thông qua mật khẩu hoặc dấu vân tay.
- [ ] 18. `Gợi nhớ ảnh`: Thời gian trong tháng sẽ có những nhắc nhở về kỉ niệm với một loạt các bức ảnh có liên quan với nhau.
- [ ] 19. `Lọc ảnh trùng`: Trong quá trình chụp ảnh sẽ có nhiều ảnh được chụp mang tính chất tương tự nhau, chức năng cung cấp các đề xuất các ảnh trùng để người dùng tương tác.
